/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package VIEW;

import CONTROLLER.ReaderController;
import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author Dat Huy
 */
public class addreader extends javax.swing.JDialog {

    /**
     * Creates new form addreader
     */
    private ReaderController readerController = new ReaderController();
    private MAINVIEW mainview;
    
    public addreader(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        mainview = (MAINVIEW) parent;
        
        hide_error_signal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("HỦY BỎ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 90, 45));

        jButton1.setText("THÊM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 85, 45));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 183, 27));

        jLabel3.setText("EMAIL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 27));

        jLabel2.setText("NĂM SINH");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, 27));
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 181, 27));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 181, 27));

        jLabel1.setText("TÊN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, 27));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("chỉ bao gồm: kí tự");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 127, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("chỉ bao gồm: số");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 131, -1));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("nhập sai email!");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 181, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = this.name.getText();
        String yearOfBirth = this.year.getText();
        String email = this.email.getText();
        boolean isOk = true;
        
        if (name.length() == 0) {
            this.name.setBorder(new LineBorder(Color.RED));
            this.jLabel4.setText("Không được để trống!");
            isOk = false;
        }
        else if (!name.matches("[\\p{L} ]+")) {
            this.name.setBorder(new LineBorder(Color.RED));
            this.jLabel4.setText("chỉ bao gồm: kí tự");
            isOk = false;
        }
        else {
            this.name.setBorder(new LineBorder(Color.BLACK));
            this.jLabel4.setText(" ");
        }
        
        if (yearOfBirth.length() == 0) {
            this.year.setBorder(new LineBorder(Color.RED));
            this.jLabel5.setText("Không được để trống!");
            isOk = false;
        }
        else if (!yearOfBirth.matches("^[1-2][0-9]{3}$")) {
            this.year.setBorder(new LineBorder(Color.RED));
            this.jLabel5.setText("chỉ gồm: số [1xxx , 2xxx]");
            isOk = false;
        }
        else {
            this.year.setBorder(new LineBorder(Color.BLACK));
            this.jLabel5.setText(" ");
        }
        
        if (email.length() == 0) {
            this.email.setBorder(new LineBorder(Color.RED));
            this.jLabel6.setText("Không được để trống!");
            isOk = false;
        }
        else if (email.matches("^[\\w-\\.]+@[\\w-]\\.[a-z]{2,4}$") || email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[a-z]{2,}$")) {
            this.email.setBorder(new LineBorder(Color.BLACK));
            this.jLabel6.setText(" ");
        }
        else {
            this.email.setBorder(new LineBorder(Color.RED));
            this.jLabel6.setText("nhập lại email!");
            isOk = false;
        }
        
        if (isOk) {
            int yearOfBirth_ = Integer.parseInt(yearOfBirth);
            readerController.add(name, yearOfBirth_, email);
            mainview.show_Reader();
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addreader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addreader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addreader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addreader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addreader dialog = new addreader(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
    void hide_error_signal () {
        this.jLabel4.setText(" ");
        this.jLabel5.setText(" ");
        this.jLabel6.setText(" ");
        
        this.name.setBorder(new LineBorder(Color.BLACK));
        this.email.setBorder((new LineBorder(Color.BLACK)));
        this.year.setBorder(new LineBorder(Color.BLACK));
    } 
}
